In [111]:
import numpy as np
import pandas as pd
import re
import networkx as nx
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import collections
import itertools
import seaborn as sns
import datetime
import nltk
from nltk.corpus import stopwords  #stopwords
from nltk.stem import WordNetLemmatizer  
from sklearn.feature_extraction.text import TfidfVectorizer
stop_words=set(nltk.corpus.stopwords.words('english')+['made', 'well', 'anyone','guys','name','much',
                                                      'put','ever','could', 'one', 'done','come','www','may',
                                                      'hey', 'chan','someday', 'still','yet','somehow',
                                                      'first', 'yoooo', '2021', '2020', 'truly', '2019',
                                                      'also', 'degree', 'units', 'skip', 'hello', 'soon', 
                                                      'even', 'really', 'going','greeting', 'come', 'next',
                                                      'looks', 'ahhhh', 'desu', 'get', 'got', 'guy', 'make', 'qua',
                                                      'watashi', 'okay', 'yuri', 'com', 'back', 'wait', 'thought',
                                                      'past'])

In [2]:
df = pd.read_excel('C:/Users/jwan0/Youtubecrawl_JP_1108.xlsx')

df.head()

,Unnamed: 0,Unnamed: 0.1,id,content of comments,Translation,text_token,text_string,text_string_fdist,text_string_lem,is_equal,neg,neu,pos,compound,sentiment
0,0,0,Alessio Barone,I LOVE JAPAN! From Italy 🇮🇹,love japan! from italy 🇮🇹,"['love', 'japan', 'italy']",love japan italy,love japan italy,love japan italy,True,0.000,0.323,0.677,0.6369,positive
1,1,1,T Take,0:01 TOKYO SKYTRE0:02 Tokyo Tower0:08 Toudai-j...,0:01 tokyo skytre0:02 tokyo tower0:08 toudai-j...,"['0', '01', 'tokyo', 'skytre0', '02', 'tokyo',...",tokyo skytre0 tokyo tower0 toudai temple0 know...,tokyo skytre0 tokyo tower0 toudai temple0 know...,tokyo skytre0 tokyo tower0 toudai temple0 know...,True,0.045,0.833,0.122,0.7506,positive
2,2,2,KF,Japan is such a wonder to me. Love from India!...,japan is such a wonder to me. love from india!...,"['japan', 'wonder', 'love', 'india']",japan wonder love india,japan wonder love india,japan wonder love india,True,0.000,0.417,0.583,0.6369,positive
3,3,3,Thijmen,I'm currently learning Japanese and when I see...,i'm currently learning japanese and when i see...,"['currently', 'learning', 'japanese', 'see', '...",currently learning japanese see video reminds ...,currently learning japanese see video reminds ...,currently learning japanese see video reminds ...,True,0.000,0.792,0.208,0.6369,positive
4,4,4,あめ,この動画を見ると改めてこの美しい国に生まれてよかったなと思います。私達日本人にも再度日本の魅...,watching this video makes me feel happy to be ...,"['watching', 'video', 'makes', 'feel', 'happy'...",watching video makes feel happy born beautiful...,watching video makes feel happy born beautiful...,watching video makes feel happy born beautiful...,True,0.000,0.442,0.558,0.9918,positive

In [3]:
df = df.astype('string')
df.dtypes

Unnamed: 0             string
Unnamed: 0.1           string
id                     string
content of comments    string
Translation            string
text_token             string
text_string            string
text_string_fdist      string
text_string_lem        string
is_equal               string
neg                    string
neu                    string
pos                    string
compound               string
sentiment              string
dtype: object

In [4]:
df = df.dropna()

df.head()

,Unnamed: 0,Unnamed: 0.1,id,content of comments,Translation,text_token,text_string,text_string_fdist,text_string_lem,is_equal,neg,neu,pos,compound,sentiment
0,0,0,Alessio Barone,I LOVE JAPAN! From Italy 🇮🇹,love japan! from italy 🇮🇹,"['love', 'japan', 'italy']",love japan italy,love japan italy,love japan italy,True,0.0,0.323,0.677,0.6369,positive
1,1,1,T Take,0:01 TOKYO SKYTRE0:02 Tokyo Tower0:08 Toudai-j...,0:01 tokyo skytre0:02 tokyo tower0:08 toudai-j...,"['0', '01', 'tokyo', 'skytre0', '02', 'tokyo',...",tokyo skytre0 tokyo tower0 toudai temple0 know...,tokyo skytre0 tokyo tower0 toudai temple0 know...,tokyo skytre0 tokyo tower0 toudai temple0 know...,True,0.045,0.833,0.122,0.7506,positive
2,2,2,KF,Japan is such a wonder to me. Love from India!...,japan is such a wonder to me. love from india!...,"['japan', 'wonder', 'love', 'india']",japan wonder love india,japan wonder love india,japan wonder love india,True,0.0,0.417,0.583,0.6369,positive
3,3,3,Thijmen,I'm currently learning Japanese and when I see...,i'm currently learning japanese and when i see...,"['currently', 'learning', 'japanese', 'see', '...",currently learning japanese see video reminds ...,currently learning japanese see video reminds ...,currently learning japanese see video reminds ...,True,0.0,0.792,0.208,0.6369,positive
4,4,4,あめ,この動画を見ると改めてこの美しい国に生まれてよかったなと思います。私達日本人にも再度日本の魅...,watching this video makes me feel happy to be ...,"['watching', 'video', 'makes', 'feel', 'happy'...",watching video makes feel happy born beautiful...,watching video makes feel happy born beautiful...,watching video makes feel happy born beautiful...,True,0.0,0.442,0.558,0.9918,positive

In [112]:
vect =TfidfVectorizer(stop_words=stop_words,max_features=1000)
vect_text=vect.fit_transform(df['text_string_lem'])

In [113]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model=LatentDirichletAllocation(n_components=10,
learning_method='online',random_state=42,max_iter=1) 
lda_top=lda_model.fit_transform(vect_text)

In [114]:
print("Document : ")
for i,topic in enumerate(lda_top[0]):
  print("Topic ",i,": ",topic*100,"%")

Document :
Topic  0 :  3.961029992262586 %
Topic  1 :  3.96153927620114 %
Topic  2 :  3.9609986339893313 %
Topic  3 :  3.9616739218013604 %
Topic  4 :  3.9665706478552116 %
Topic  5 :  3.9609164762650715 %
Topic  6 :  3.9608862153255613 %
Topic  7 :  64.34434634450264 %
Topic  8 :  3.961073946720943 %
Topic  9 :  3.960964545076142 %

In [115]:
vocab = vect.get_feature_names()
for i, comp in enumerate(lda_model.components_):
     vocab_comp = zip(vocab, comp)
     sorted_words = sorted(vocab_comp, key= lambda x:x[1], reverse=True)[:10]
     print("Topic "+str(i)+": ")
     for t in sorted_words:
            print(t[0],end=" ")
            print('\n')

Topic 0:
japanese

glad

know

japan

born

sorry

proud

foreigners

video

wasabi

Topic 1:
hiroshima

fukushima

cambodia

cakes

rice

love

perfect

learn

situation

transition

Topic 2:
cool

like

japan

people

child

dream

video

kind

images

thank

Topic 3:
beautiful

japan

wow

live

love

country

visit

best

place

china

Topic 4:
japan

love

nice

india

thank

like

indonesia

coming

respect

video

Topic 5:
awesome

culture

nakagawa

homeland

mochi

japan

class

country

thai

like

Topic 6:
girl

japan

pride

park

green

tear

куваева

perfectionist

подруга

сергея

Topic 7:
want

japan

good

love

video

korea

visit

country

know

old

Topic 8:
anime

movie

work

awesome

camera

wearing

outfit

special

miss

beautifully

Topic 9:
video

amazing

great

music

wonderful

song

youtube

country

know

japan